<?php
    session_start();
    include("../Dao.php");
    $username=$_SESSION["username"];
    $password=$_POST["password"];
    $name=$_POST["name"];
    $email=$_POST["email"];
    $phone=$_POST["phone"];
    $address=$_POST["address"];
    $image=$_POST["image"];
    if($name==null)
        $name="";
    if($phone==null)
        $phone="";
    if($address==null)
        $address="";
    if($email==null)
        $email="";
    //包成JSON
    $member=array("password"=>$password,"name"=>$name,"email"=>$email,"phone"=>$phone,"address"=>$address,"image"=>$image);
    $json=json_encode($member);
    //資料庫   
    $dao=new Firebase();
    $dao->editMember($username,$json);
?>